config/routes.rb
Rails.application.routes.draw do
  get 'airports/index'
  get 'flights/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "destination_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: "Airport", foreign_key: "departure_airport_id"
    belongs_to :destination_airport, class_name: "Airport", foreign_key: "destination_airport_id"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def index
    @airports = Airport.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all

    @available_flights = Flight.where(departure_airport: params[:departure_airport], destination_airport: params[:destination_airport], 
    flight_time: params[:flight_time], flight_date: params[:flight_date])
  end

  private
  def flight_search_params
    params.require(:flight).permit(:departure_airport_id, :destination_airport_id, :flight_time, :flight_date)
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/airports/index.html.erb
<h1>Airports#index</h1>
<p>Find me in app/views/airports/index.html.erb</p>

app/views/flights/_flight_search_form.html.erb
<%= form_with url: flights_index_path, method: :get, local: true do |form| %>
    <h3>Search for flights</h3>

    <% @airports = Airport.all.map { |airport| [airport.airport_code, airport.id] } %>
    <% @flight_dates = Flight.all.map { |flight| [flight.flight_date.strftime("%m/%d/%Y")] } %>
    <% @flight_times = Flight.all.map { |flight| [flight.flight_time.strftime("%I:%M%p")] } %>
    <% @flights = Flight.all.map { |flight| [flight.id] } %>
    <% @passengers = [1,2,3,4] %>

    <div>
        <%= form.label :departure_location %> <br>
        <%= select_tag(:departure_airport, options_for_select(@airports, selected: params[:departure_airport_id])) %>
    </div>

    <br>

    <div>
        <%= form.label :destination_location %> <br>
        <%= select_tag(:destination_airport, options_for_select(@airports, selected: params[:destination_airport_id])) %>
    </div>

    <br>
        
    <div>
        <%= form.label :date %> <br>
        <%= select_tag(:flight_date, options_for_select(@flight_dates, selected: params[:flight_date])) %>
    </div>

    <br>

    <div>
        <%= form.label :time %> <br>
        <%= select_tag(:flight_time, options_for_select(@flight_times, selected: params[:flight_time])) %>
    </div>

    <br>

    <div>
        <%= form.label :passengers %> <br>
        <%= select_tag(:passengers, options_for_select(@passengers))%>
    </div>

    <br>

    <%= form.submit "choose flight" %>
<% end %>

app/views/flights/_flight_search_result_form.html.erb
<h1>Search result form</h1>

<%= form_with url: flights_index_path, method: :get, local: true do |form| %>
    <% if @available_flights == [] %>
        <p>All Flights</p>

        <% @flights.each do |flight| %>
        <div>
        <%= form.radio_button :flight, "flight" %>
            <%= flight %>
        </div>
        <% end %>
    <% else %>
    <p>Results</p>
        <% @available_flights.each do |flight| %>
        <div>
        <%= form.radio_button :flight, "flight" %>
            <%= flight.id %>
        </div>
        <% end %>

        <%= form.submit "Select flight" %>
    <% end %>
<% end %>

app/views/flights/index.html.erb
<h1>This is the flights search page!</h1>

<div>
    <%= render "flight_search_form" %>
</div>

<div>
    <%= render "flight_search_result_form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>